### ISSUE TITLE
Cannot write to files

### ISSUE THREAD

**Issue by mbootsman** [sparanoid/docker-php-fpm#10]
Hi thanks for this image, because I need bcmath for a project, I decided to use this image.

I have one problem though, I need to write to a file for this project, and I keep getting this error:
`NOTICE: PHP message: PHP Warning:  file_put_contents(file.txt): Failed to open stream: Permission denied in /var/www/html/filetest.php on line 4`

`/var/www/html` is mapped to a local directory, like `/app` in the original docker-compose file here: https://hub.docker.com/r/sparanoid/php-fpm

**Comment by sparanoid** [comment]
Can you provide a repo with the script and docker compose file you're using so I can reproduce it? Thanks!

**Comment by sparanoid** [comment]
From the info you provided I guess the permission of the directory you mounted is wrong. You can try:

```shell
$ docker exec php_container_name id www-data
uid=33(www-data) gid=33(www-data) groups=33(www-data)
```

Then change the owner of your mounted volume:

```shell
chown 33:33 -R /var/www/html
```

**Comment by mbootsman** [comment]
> Can you provide a repo with the script and docker compose file you're using so I can reproduce it? Thanks!

Thanks for your fast reply!

Sure, [here](https://gist.github.com/mbootsman/8442b8678b14d11516845272bcf3e75b) is the script.
And [here](https://gist.github.com/mbootsman/c9919ce0358eafeaef05f7c52dc627ef) is my docker-compose file.

**Comment by mbootsman** [comment]
> From the info you provided I guess the permission of the directory you mounted is wrong. You can try:
> 
> ```shell
> $ docker exec php_container_name id www-data
> uid=33(www-data) gid=33(www-data) groups=33(www-data)
> ```
> 
> Then change the owner of your mounted volume:
> 
> ```shell
> chown 33:33 -R /var/www/html
> ```
I'll wait for you to see if you can reproduce and solve the problem first :wink:

**Comment by sparanoid** [comment]
> I'll wait for you to see if you can reproduce and solve the problem first 😉

Hi, I was unable to reproduce it. It works for me and creates the correct file when access the `filetest.php` served from Nginx:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/96356/203787297-d2b58b70-f9a0-458e-8d9e-9a627a7ed7f8.png">

Can you try the solution mentioned in previous comment?

My environment: macOS 12.6 (21G115) with Docker Desktop 4.12.0

**Comment by mbootsman** [comment]
> Hi, I was unable to reproduce it. It works for me and creates the correct file when access the `filetest.php` served from Nginx:

Hmm, that's odd. Thanks for testing.

What do these commands do?
And where do I need to execute the second command? On my host, or from within the container?

Edit:
I have changed /var/www/html to /app, as in your original files.

From within the container, I see the files in /app. 
This is what I see for file.txt
`-rw-rw-r-- 1 1000 1000       3 Nov 24 13:16 file.txt`

And now something hit me. What if I delete the file, and let PHP create it....
Now it works.
